import React, { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // General
    appName: 'MedConnect',
    tagline: 'Your trusted local pharmacy network — find medicines, reserve with ease.',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    back: 'Back',
    logout: 'Logout',
    profile: 'My Profile',
    yes: 'Yes',
    no: 'No',
    actions: 'Actions',
    status: 'Status',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    notes: 'Notes',
    quantity: 'Quantity',
    price: 'Price',
    date: 'Date',
    noData: 'No data found.',
    language: 'Language',

    // Auth
    welcomeBack: 'Welcome Back',
    signIn: 'Sign in to your account',
    signInBtn: 'Sign In',
    signingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    emailAddress: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    patient: 'Patient',
    pharmacy: 'Pharmacy',
    superAdmin: 'Super Admin',
    features: [
      'Find medicines at nearby pharmacies',
      'Upload prescriptions securely',
      'Track your reservations easily',
      'AI-powered medicine suggestions',
    ],

    // Navigation
    dashboard: 'Dashboard',
    searchMedicines: 'Search Medicines',
    myReservations: 'My Reservations',
    inventory: 'Inventory',
    medicines: 'Medicines',
    pharmacies: 'Pharmacies',
    reservations: 'Reservations',

    // Dashboard
    hello: 'Hello',
    findMedicines: 'Find medicines at nearby pharmacies and manage your reservations',
    totalReservations: 'Total Reservations',
    activeReservations: 'Active Reservations',
    completed: 'Completed',
    recentReservations: 'Recent Reservations',
    noReservations: 'No reservations yet. Search for a medicine to get started!',
    pharmacyDashboard: 'Pharmacy Dashboard',
    welcomeBack2: 'Welcome back',
    pharmacyOverview: "here's your pharmacy overview",
    totalInventory: 'Total Inventory Items',
    lowStock: 'Low Stock Items',
    activeToday: 'Active Today',
    realtimeData: 'Real-time data',
    lowStockAlert: '⚠️ Low Stock Alert — Action Required',
    allWellStocked: '✅ All items are well stocked!',
    noRecentReservations: 'No reservations yet.',
    lowStockItems: 'Low Stock Items',
    overviewStats: 'Overview Stats',
    totalPharmacies: 'Total Pharmacies',
    totalMedicines: 'Total Medicines',
    activePharmacies: 'Active Pharmacies',

    // Search
    searchMedicinesTitle: 'Search Medicines',
    searchSubtitle: 'Find medicines at pharmacies near you or upload your prescription',
    searchPlaceholder: 'Search by medicine name (e.g. Paracetamol, Dolo 650)...',
    searching: 'Searching...',
    aiSuggestion: 'AI Suggestion — You might also try:',
    uploadPrescription: 'Upload Prescription',
    uploadSubtitle: 'Some medicines require a valid prescription. Upload yours before reserving.',
    dragDrop: 'Drag & drop prescription here, or click to browse',
    fileSupport: 'Supports JPG, PNG, PDF • Max 5MB',
    noMedicinesFound: 'No medicines found for',
    tryDifferent: 'Try a different name.',
    found: 'Found',
    medicine: 'medicine',
    medicines2: 'medicines',
    tapToSeePharmacies: '— tap to see nearby pharmacies',
    nearbyPharmacies: 'Nearby Pharmacies (nearest first)',
    loadingPharmacies: 'Loading nearby pharmacies...',
    noNearbyPharmacies: 'No nearby pharmacies found with this medicine in stock.',
    prescriptionRequired: 'Prescription Required',
    prescriptionRequiredMsg: 'Please upload your prescription above before you can reserve this medicine.',
    reserve: 'Reserve',
    nearest: '📍 Nearest',
    confirmReservation: 'Confirm Reservation',
    reserving: 'Reserving...',
    confirmReservationBtn: 'Confirm Reservation',
    specialInstructions: 'Any special instructions...',
    notesToPharmacy: 'Notes to Pharmacy (optional)',
    prescriptionAttached: 'Prescription attached:',
    prescriptionNeeded: 'Upload prescription above to reserve this medicine',
    overTheCounter: '✓ Over the Counter',
    prescriptionNeededBadge: '📋 Prescription Needed',
    gettingLocation: 'Getting your location...',
    locationDenied: 'Location access denied. Showing all pharmacies.',
    kmAway: 'km away',
    locatingNearby: 'Locating nearby pharmacies...',
    useMyLocation: 'Use My Location',

    // Reservations
    myReservationsTitle: 'My Reservations',
    noReservationsYet: 'No reservations yet.',
    uploadPrescriptionFor: 'Upload Prescription for',
    viewPrescription: 'View Prescription',
    cancelReservation: 'Cancel Reservation',
    confirmCancel: 'Are you sure you want to cancel this reservation?',
    pending: 'Pending',
    confirmed: 'Confirmed',
    success: 'Success',
    rejected: 'Rejected',
    cancelled: 'Cancelled',

    // Profile
    myProfileTitle: 'My Profile',
    profileInfo: 'Profile Information',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    updateProfile: 'Update Profile',
    updatePassword: 'Update Password',

    // Admin
    adminInventoryTitle: 'Inventory Management',
    addInventory: 'Add Inventory',
    medicineName: 'Medicine Name',
    unit: 'Unit',
    expiryDate: 'Expiry Date',
    reorderLevel: 'Reorder Level',
    adminMedicinesTitle: 'Medicines',
    addMedicine: 'Add Medicine',
    genericName: 'Generic Name',
    category: 'Category',
    manufacturer: 'Manufacturer',
    dosage: 'Dosage',
    requiresPrescription: 'Requires Prescription',
    adminReservationsTitle: 'Reservations',
    updateStatus: 'Update Status',
    user: 'User',
    pharmacyName: 'Pharmacy',

    // SuperAdmin
    saPharmaciesTitle: 'Manage Pharmacies',
    addPharmacy: 'Add Pharmacy',
    licenseNumber: 'License Number',
    active: 'Active',
    inactive: 'Inactive',
    saMedicinesTitle: 'Global Medicines',

    // Errors/Messages
    fillAllFields: 'Please fill all fields',
    loginFailed: 'Login failed. Please try again.',
    searchFailed: 'Search failed',
    reservationSuccess: 'Reservation created successfully! 🎉',
    reservationFailed: 'Reservation failed',
    profileUpdated: 'Profile updated successfully!',
    passwordUpdated: 'Password updated successfully!',
    loggedOut: 'Logged out successfully',

    // 404/Unauthorized
    pageNotFound: 'Page not found',
    pageNotFoundMsg: 'The page you are looking for does not exist.',
    goHome: 'Go Home',
    accessDenied: 'Access Denied',
    noPermission: 'You do not have permission to view this page.',
    goBack: 'Go Back',
  },

  ta: {
    // General
    appName: 'மெட்கனெக்ட்',
    tagline: 'உங்கள் நம்பகமான உள்ளூர் மருந்தகம் — மருந்துகளை எளிதாக கண்டுபிடிக்க, ஒதுக்கீடு செய்ய.',
    loading: 'ஏற்றுகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    view: 'பார்',
    close: 'மூடு',
    confirm: 'உறுதிப்படுத்து',
    search: 'தேடு',
    add: 'சேர்',
    create: 'உருவாக்கு',
    update: 'புதுப்பி',
    back: 'பின்செல்',
    logout: 'வெளியேறு',
    profile: 'என் சுயவிவரம்',
    yes: 'ஆம்',
    no: 'இல்லை',
    actions: 'செயல்கள்',
    status: 'நிலை',
    name: 'பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    address: 'முகவரி',
    city: 'நகரம்',
    notes: 'குறிப்புகள்',
    quantity: 'அளவு',
    price: 'விலை',
    date: 'தேதி',
    noData: 'தகவல் இல்லை.',
    language: 'மொழி',

    // Auth
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signIn: 'உங்கள் கணக்கில் உள்நுழையவும்',
    signInBtn: 'உள்நுழை',
    signingIn: 'உள்நுழைகிறது...',
    noAccount: 'கணக்கு இல்லையா?',
    createOne: 'புதிதாக உருவாக்கு',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல் உறுதிப்படுத்து',
    fullName: 'முழு பெயர்',
    createAccount: 'கணக்கு உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signInLink: 'உள்நுழை',
    patient: 'நோயாளி',
    pharmacy: 'மருந்தகம்',
    superAdmin: 'சூப்பர் அட்மின்',
    features: [
      'அருகிலுள்ள மருந்தகங்களில் மருந்துகளை கண்டுபிடிக்கவும்',
      'பிரிஸ்கிரிப்ஷன்களை பாதுகாப்பாக பதிவேற்றவும்',
      'உங்கள் ஒதுக்கீடுகளை எளிதாக கண்காணிக்கவும்',
      'AI-இயங்கும் மருந்து பரிந்துரைகள்',
    ],

    // Navigation
    dashboard: 'டாஷ்போர்டு',
    searchMedicines: 'மருந்துகளை தேடு',
    myReservations: 'என் ஒதுக்கீடுகள்',
    inventory: 'சரக்கு',
    medicines: 'மருந்துகள்',
    pharmacies: 'மருந்தகங்கள்',
    reservations: 'ஒதுக்கீடுகள்',

    // Dashboard
    hello: 'வணக்கம்',
    findMedicines: 'அருகிலுள்ள மருந்தகங்களில் மருந்துகளை கண்டுபிடித்து உங்கள் ஒதுக்கீடுகளை நிர்வகிக்கவும்',
    totalReservations: 'மொத்த ஒதுக்கீடுகள்',
    activeReservations: 'செயலில் உள்ள ஒதுக்கீடுகள்',
    completed: 'முடிந்தது',
    recentReservations: 'சமீபத்திய ஒதுக்கீடுகள்',
    noReservations: 'இன்னும் ஒதுக்கீடுகள் இல்லை. தொடங்க மருந்தை தேடுங்கள்!',
    pharmacyDashboard: 'மருந்தக டாஷ்போர்டு',
    welcomeBack2: 'மீண்டும் வரவேற்கிறோம்',
    pharmacyOverview: 'உங்கள் மருந்தக கண்ணோட்டம்',
    totalInventory: 'மொத்த சரக்கு பொருட்கள்',
    lowStock: 'குறைந்த இருப்பு',
    activeToday: 'இன்று செயல்',
    realtimeData: 'நிகழ்நேர தரவு',
    lowStockAlert: '⚠️ குறைந்த இருப்பு எச்சரிக்கை — நடவடிக்கை தேவை',
    allWellStocked: '✅ அனைத்தும் போதுமான அளவு உள்ளது!',
    noRecentReservations: 'இன்னும் ஒதுக்கீடுகள் இல்லை.',
    lowStockItems: 'குறைந்த இருப்பு பொருட்கள்',
    overviewStats: 'கண்ணோட்ட புள்ளிவிவரங்கள்',
    totalPharmacies: 'மொத்த மருந்தகங்கள்',
    totalMedicines: 'மொத்த மருந்துகள்',
    activePharmacies: 'செயலில் உள்ள மருந்தகங்கள்',

    // Search
    searchMedicinesTitle: 'மருந்துகளை தேடு',
    searchSubtitle: 'உங்களுக்கு அருகிலுள்ள மருந்தகங்களில் மருந்துகளை கண்டுபிடிக்கவும்',
    searchPlaceholder: 'மருந்தின் பெயரை தேடுங்கள் (எ.கா. பாராசிட்டமால், டோலோ 650)...',
    searching: 'தேடுகிறது...',
    aiSuggestion: 'AI பரிந்துரை — இவற்றையும் முயற்சிக்கலாம்:',
    uploadPrescription: 'பிரிஸ்கிரிப்ஷன் பதிவேற்று',
    uploadSubtitle: 'சில மருந்துகளுக்கு சரியான மருத்துவ சீட்டு தேவை. ஒதுக்குவதற்கு முன் பதிவேற்றவும்.',
    dragDrop: 'பிரிஸ்கிரிப்ஷனை இங்கே இழுத்து விடுங்கள் அல்லது கிளிக் செய்யுங்கள்',
    fileSupport: 'JPG, PNG, PDF ஆதரிக்கப்படும் • அதிகபட்சம் 5MB',
    noMedicinesFound: 'எந்த மருந்தும் கிடைக்கவில்லை:',
    tryDifferent: 'வேறு பெயரை முயற்சிக்கவும்.',
    found: 'கண்டுபிடிக்கப்பட்டது',
    medicine: 'மருந்து',
    medicines2: 'மருந்துகள்',
    tapToSeePharmacies: '— மருந்தகங்களைப் பார்க்க தொட்டுவிடுங்கள்',
    nearbyPharmacies: 'அருகிலுள்ள மருந்தகங்கள் (மிக அருகில் முதலில்)',
    loadingPharmacies: 'அருகிலுள்ள மருந்தகங்களை ஏற்றுகிறது...',
    noNearbyPharmacies: 'இந்த மருந்துடன் இருப்பில் அருகிலுள்ள மருந்தகங்கள் இல்லை.',
    prescriptionRequired: 'மருத்துவ சீட்டு தேவை',
    prescriptionRequiredMsg: 'இந்த மருந்தை ஒதுக்குவதற்கு முன் மேலே உங்கள் மருத்துவ சீட்டை பதிவேற்றவும்.',
    reserve: 'ஒதுக்கு',
    nearest: '📍 மிக அருகில்',
    confirmReservation: 'ஒதுக்கீட்டை உறுதிப்படுத்து',
    reserving: 'ஒதுக்குகிறது...',
    confirmReservationBtn: 'ஒதுக்கீட்டை உறுதிப்படுத்து',
    specialInstructions: 'சிறப்பு அறிவுரைகள்...',
    notesToPharmacy: 'மருந்தகத்திற்கு குறிப்புகள் (விருப்பமானது)',
    prescriptionAttached: 'மருத்துவ சீட்டு இணைக்கப்பட்டுள்ளது:',
    prescriptionNeeded: 'இந்த மருந்தை ஒதுக்க மேலே மருத்துவ சீட்டை பதிவேற்றவும்',
    overTheCounter: '✓ மருத்துவர் பரிந்துரை இல்லாமல்',
    prescriptionNeededBadge: '📋 மருத்துவ சீட்டு தேவை',
    gettingLocation: 'உங்கள் இருப்பிடத்தை கண்டறிகிறது...',
    locationDenied: 'இருப்பிட அணுகல் மறுக்கப்பட்டது. அனைத்து மருந்தகங்களும் காட்டப்படுகின்றன.',
    kmAway: 'கி.மீ தொலைவில்',
    locatingNearby: 'அருகிலுள்ள மருந்தகங்களை கண்டறிகிறது...',
    useMyLocation: 'என் இருப்பிடத்தை பயன்படுத்து',

    // Reservations
    myReservationsTitle: 'என் ஒதுக்கீடுகள்',
    noReservationsYet: 'இன்னும் ஒதுக்கீடுகள் இல்லை.',
    uploadPrescriptionFor: 'பிரிஸ்கிரிப்ஷன் பதிவேற்று',
    viewPrescription: 'மருத்துவ சீட்டை பார்',
    cancelReservation: 'ஒதுக்கீட்டை ரத்து செய்',
    confirmCancel: 'இந்த ஒதுக்கீட்டை ரத்து செய்ய விரும்புகிறீர்களா?',
    pending: 'நிலுவையில்',
    confirmed: 'உறுதிப்படுத்தப்பட்டது',
    success: 'வெற்றி',
    rejected: 'நிராகரிக்கப்பட்டது',
    cancelled: 'ரத்து செய்யப்பட்டது',

    // Profile
    myProfileTitle: 'என் சுயவிவரம்',
    profileInfo: 'சுயவிவர தகவல்',
    changePassword: 'கடவுச்சொல் மாற்று',
    currentPassword: 'தற்போதைய கடவுச்சொல்',
    newPassword: 'புதிய கடவுச்சொல்',
    updateProfile: 'சுயவிவரத்தை புதுப்பி',
    updatePassword: 'கடவுச்சொல்லை புதுப்பி',

    // Admin
    adminInventoryTitle: 'சரக்கு மேலாண்மை',
    addInventory: 'சரக்கு சேர்',
    medicineName: 'மருந்தின் பெயர்',
    unit: 'அலகு',
    expiryDate: 'காலாவதி தேதி',
    reorderLevel: 'மறுஆர்டர் அளவு',
    adminMedicinesTitle: 'மருந்துகள்',
    addMedicine: 'மருந்து சேர்',
    genericName: 'பொதுப் பெயர்',
    category: 'வகை',
    manufacturer: 'உற்பத்தியாளர்',
    dosage: 'அளவு',
    requiresPrescription: 'மருத்துவ சீட்டு தேவை',
    adminReservationsTitle: 'ஒதுக்கீடுகள்',
    updateStatus: 'நிலையை புதுப்பி',
    user: 'பயனர்',
    pharmacyName: 'மருந்தகம்',

    // SuperAdmin
    saPharmaciesTitle: 'மருந்தகங்களை நிர்வகி',
    addPharmacy: 'மருந்தகம் சேர்',
    licenseNumber: 'உரிம எண்',
    active: 'செயலில்',
    inactive: 'செயலற்று',
    saMedicinesTitle: 'அனைத்து மருந்துகள்',

    // Errors/Messages
    fillAllFields: 'அனைத்து புலங்களையும் நிரப்பவும்',
    loginFailed: 'உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    searchFailed: 'தேடல் தோல்வியடைந்தது',
    reservationSuccess: 'ஒதுக்கீடு வெற்றிகரமாக உருவாக்கப்பட்டது! 🎉',
    reservationFailed: 'ஒதுக்கீடு தோல்வியடைந்தது',
    profileUpdated: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    passwordUpdated: 'கடவுச்சொல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    loggedOut: 'வெற்றிகரமாக வெளியேறினீர்கள்',

    // 404/Unauthorized
    pageNotFound: 'பக்கம் கிடைக்கவில்லை',
    pageNotFoundMsg: 'நீங்கள் தேடும் பக்கம் இல்லை.',
    goHome: 'முகப்பிற்கு செல்',
    accessDenied: 'அணுகல் மறுக்கப்பட்டது',
    noPermission: 'இந்தப் பக்கத்தை பார்க்க உங்களுக்கு அனுமதி இல்லை.',
    goBack: 'பின்செல்',
  },

  hi: {
    // General
    appName: 'मेडकनेक्ट',
    tagline: 'आपका विश्वसनीय स्थानीय फार्मेसी नेटवर्क — दवाइयाँ खोजें, आसानी से बुक करें।',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    view: 'देखें',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
    search: 'खोजें',
    add: 'जोड़ें',
    create: 'बनाएं',
    update: 'अपडेट करें',
    back: 'वापस',
    logout: 'लॉग आउट',
    profile: 'मेरी प्रोफ़ाइल',
    yes: 'हाँ',
    no: 'नहीं',
    actions: 'कार्रवाई',
    status: 'स्थिति',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फ़ोन',
    address: 'पता',
    city: 'शहर',
    notes: 'नोट्स',
    quantity: 'मात्रा',
    price: 'कीमत',
    date: 'तारीख',
    noData: 'कोई डेटा नहीं मिला।',
    language: 'भाषा',

    // Auth
    welcomeBack: 'वापस स्वागत है',
    signIn: 'अपने खाते में साइन इन करें',
    signInBtn: 'साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    noAccount: 'खाता नहीं है?',
    createOne: 'नया बनाएं',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    createAccount: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से खाता है?',
    signInLink: 'साइन इन करें',
    patient: 'मरीज़',
    pharmacy: 'फार्मेसी',
    superAdmin: 'सुपर एडमिन',
    features: [
      'नजदीकी फार्मेसियों में दवाइयाँ खोजें',
      'पर्चे सुरक्षित रूप से अपलोड करें',
      'अपनी बुकिंग आसानी से ट्रैक करें',
      'AI-आधारित दवाई सुझाव',
    ],

    // Navigation
    dashboard: 'डैशबोर्ड',
    searchMedicines: 'दवाइयाँ खोजें',
    myReservations: 'मेरी बुकिंग',
    inventory: 'इन्वेंटरी',
    medicines: 'दवाइयाँ',
    pharmacies: 'फार्मेसियाँ',
    reservations: 'बुकिंग',

    // Dashboard
    hello: 'नमस्ते',
    findMedicines: 'नजदीकी फार्मेसियों में दवाइयाँ खोजें और अपनी बुकिंग प्रबंधित करें',
    totalReservations: 'कुल बुकिंग',
    activeReservations: 'सक्रिय बुकिंग',
    completed: 'पूर्ण',
    recentReservations: 'हाल की बुकिंग',
    noReservations: 'अभी तक कोई बुकिंग नहीं। शुरू करने के लिए दवा खोजें!',
    pharmacyDashboard: 'फार्मेसी डैशबोर्ड',
    welcomeBack2: 'वापस स्वागत है',
    pharmacyOverview: 'आपकी फार्मेसी का अवलोकन',
    totalInventory: 'कुल इन्वेंटरी आइटम',
    lowStock: 'कम स्टॉक आइटम',
    activeToday: 'आज सक्रिय',
    realtimeData: 'रियल-टाइम डेटा',
    lowStockAlert: '⚠️ कम स्टॉक अलर्ट — कार्रवाई आवश्यक',
    allWellStocked: '✅ सभी आइटम पर्याप्त स्टॉक में हैं!',
    noRecentReservations: 'अभी तक कोई बुकिंग नहीं।',
    lowStockItems: 'कम स्टॉक आइटम',
    overviewStats: 'अवलोकन आँकड़े',
    totalPharmacies: 'कुल फार्मेसियाँ',
    totalMedicines: 'कुल दवाइयाँ',
    activePharmacies: 'सक्रिय फार्मेसियाँ',

    // Search
    searchMedicinesTitle: 'दवाइयाँ खोजें',
    searchSubtitle: 'अपने नजदीक फार्मेसियों में दवाइयाँ खोजें या पर्चा अपलोड करें',
    searchPlaceholder: 'दवाई का नाम खोजें (जैसे पैरासिटामोल, डोलो 650)...',
    searching: 'खोज रहा है...',
    aiSuggestion: 'AI सुझाव — आप यह भी आज़माएं:',
    uploadPrescription: 'पर्चा अपलोड करें',
    uploadSubtitle: 'कुछ दवाओं के लिए वैध पर्चा जरूरी है। बुकिंग से पहले अपलोड करें।',
    dragDrop: 'पर्चा यहाँ खींचें और छोड़ें, या क्लिक करें',
    fileSupport: 'JPG, PNG, PDF समर्थित • अधिकतम 5MB',
    noMedicinesFound: 'कोई दवाई नहीं मिली:',
    tryDifferent: 'कोई अलग नाम आज़माएं।',
    found: 'मिली',
    medicine: 'दवाई',
    medicines2: 'दवाइयाँ',
    tapToSeePharmacies: '— नजदीकी फार्मेसियाँ देखने के लिए टैप करें',
    nearbyPharmacies: 'नजदीकी फार्मेसियाँ (सबसे पास पहले)',
    loadingPharmacies: 'नजदीकी फार्मेसियाँ लोड हो रही हैं...',
    noNearbyPharmacies: 'इस दवाई के साथ कोई नजदीकी फार्मेसी नहीं मिली।',
    prescriptionRequired: 'पर्चा आवश्यक',
    prescriptionRequiredMsg: 'इस दवाई को बुक करने से पहले कृपया ऊपर अपना पर्चा अपलोड करें।',
    reserve: 'बुक करें',
    nearest: '📍 सबसे पास',
    confirmReservation: 'बुकिंग की पुष्टि करें',
    reserving: 'बुक हो रहा है...',
    confirmReservationBtn: 'बुकिंग की पुष्टि करें',
    specialInstructions: 'कोई विशेष निर्देश...',
    notesToPharmacy: 'फार्मेसी को नोट्स (वैकल्पिक)',
    prescriptionAttached: 'पर्चा जोड़ा गया:',
    prescriptionNeeded: 'इस दवाई को बुक करने के लिए ऊपर पर्चा अपलोड करें',
    overTheCounter: '✓ बिना पर्चे के',
    prescriptionNeededBadge: '📋 पर्चा जरूरी',
    gettingLocation: 'आपकी लोकेशन पता की जा रही है...',
    locationDenied: 'लोकेशन एक्सेस अस्वीकृत। सभी फार्मेसियाँ दिखाई जा रही हैं।',
    kmAway: 'किमी दूर',
    locatingNearby: 'नजदीकी फार्मेसियाँ ढूंढ रहा है...',
    useMyLocation: 'मेरी लोकेशन उपयोग करें',

    // Reservations
    myReservationsTitle: 'मेरी बुकिंग',
    noReservationsYet: 'अभी तक कोई बुकिंग नहीं।',
    uploadPrescriptionFor: 'पर्चा अपलोड करें',
    viewPrescription: 'पर्चा देखें',
    cancelReservation: 'बुकिंग रद्द करें',
    confirmCancel: 'क्या आप इस बुकिंग को रद्द करना चाहते हैं?',
    pending: 'प्रतीक्षा में',
    confirmed: 'पुष्टि हुई',
    success: 'सफल',
    rejected: 'अस्वीकृत',
    cancelled: 'रद्द',

    // Profile
    myProfileTitle: 'मेरी प्रोफ़ाइल',
    profileInfo: 'प्रोफ़ाइल जानकारी',
    changePassword: 'पासवर्ड बदलें',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    updatePassword: 'पासवर्ड अपडेट करें',

    // Admin
    adminInventoryTitle: 'इन्वेंटरी प्रबंधन',
    addInventory: 'इन्वेंटरी जोड़ें',
    medicineName: 'दवाई का नाम',
    unit: 'इकाई',
    expiryDate: 'समाप्ति तिथि',
    reorderLevel: 'री-ऑर्डर स्तर',
    adminMedicinesTitle: 'दवाइयाँ',
    addMedicine: 'दवाई जोड़ें',
    genericName: 'जेनेरिक नाम',
    category: 'श्रेणी',
    manufacturer: 'निर्माता',
    dosage: 'खुराक',
    requiresPrescription: 'पर्चा आवश्यक',
    adminReservationsTitle: 'बुकिंग',
    updateStatus: 'स्थिति अपडेट करें',
    user: 'उपयोगकर्ता',
    pharmacyName: 'फार्मेसी',

    // SuperAdmin
    saPharmaciesTitle: 'फार्मेसियाँ प्रबंधित करें',
    addPharmacy: 'फार्मेसी जोड़ें',
    licenseNumber: 'लाइसेंस नंबर',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    saMedicinesTitle: 'सभी दवाइयाँ',

    // Errors/Messages
    fillAllFields: 'कृपया सभी फ़ील्ड भरें',
    loginFailed: 'लॉगिन विफल। कृपया पुनः प्रयास करें।',
    searchFailed: 'खोज विफल',
    reservationSuccess: 'बुकिंग सफलतापूर्वक बनाई गई! 🎉',
    reservationFailed: 'बुकिंग विफल',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    passwordUpdated: 'पासवर्ड सफलतापूर्वक अपडेट किया गया!',
    loggedOut: 'सफलतापूर्वक लॉग आउट किया गया',

    // 404/Unauthorized
    pageNotFound: 'पृष्ठ नहीं मिला',
    pageNotFoundMsg: 'जिस पृष्ठ को आप खोज रहे हैं वह मौजूद नहीं है।',
    goHome: 'होम जाएं',
    accessDenied: 'पहुँच अस्वीकृत',
    noPermission: 'आपको इस पृष्ठ को देखने की अनुमति नहीं है।',
    goBack: 'वापस जाएं',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('medconnect_lang') || 'en')

  const changeLang = (l) => {
    setLang(l)
    localStorage.setItem('medconnect_lang', l)
  }

  const t = (key) => {
    const val = translations[lang]?.[key]
    if (val === undefined) return translations['en']?.[key] || key
    return val
  }

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider')
  return ctx
}

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
]
